config/routes.rb
Rails.application.routes.draw do
  resources :articles, except: [:delete]

  delete "articles/:id", to: "articles#destroy", as: "destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to article_path(@article)
    else
      redirect_to articles_new_path
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to article_path(@article)
    else
      redirect_to edit_article_path(@article)
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :content)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<div class="articles-container">
  <h1>Edit article</h1>
  <%= render 'layouts/form', article: @article %>
</div>

app/views/articles/index.html.erb
<div class="articles-container">
  <h1>All articles</h1>
  <% @articles.each do |article| %>
    <div class="article-box"><a href="/articles/<%= article.id %>"><%= article.title %></a> <%= link_to "", edit_article_path(article), class: "list-item fas fa-edit" %>
        <%= link_to "", destroy_path(article), class: "fas fa-trash-alt trash",
              method: :delete,
              data: { confirm: "Are you sure?" } %></div>
  <% end %>

  <%= link_to "Create new article", new_article_path %>
</div>

app/views/articles/new.html.erb
<div class="articles-container">
  <h1>Create a new article</h1>
  <%= render 'layouts/form', article: @article %>
</div>

app/views/articles/show.html.erb
<div class="articles-container">
  <h1><%= @article.title %></h1>
  <div class="article-box">
    <%= @article.content %> <%= link_to "", edit_article_path(@article), class: "list-item fas fa-edit" %>
        <%= link_to "", destroy_path(@article), class: "fas fa-trash-alt trash",
              method: :delete,
              data: { confirm: "Are you sure?" } %>
   </div>
  <%= link_to "Back to index", articles_path %>

 </div>

app/views/layouts/_form.html.erb
<div class="article-box">
  <ul>
  <%= form_for @article, :html => { :id => "form-edit" } do |f| %>
    <li>
    <%= f.label :title %>
    <%= f.text_field :title %>
    </li>
    <li>
    <%= f.label :content %>
    <%= f.text_field :content %>
    </li>
    <%= f.submit %>
  <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css" integrity="sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>